function dsl_demo()

%% Parameter Setup
run matconvnet/matlab/vl_setupnn;
addpath('matconvnet/examples');
addpath('support');
dataDir = 'image';
modelDir = 'model';
expDirRoot = 'result';
expDirDL = fullfile(expDirRoot, '1_DL');
expDirSL = fullfile(expDirRoot, '2_SL');
expDirDC = fullfile(expDirRoot, '3_DC');
gpus = 1; % gpus = 1: GPU mode; gpus = []: CPU-only mode

%% Prepare data
imdb = dsl_dataSetup('dataDir', dataDir,...
    'modelDir', modelDir,...
    'imdbPath', fullfile(dataDir, 'imdb.mat'),...
    'gpus', gpus);

%% Step 1 FCN: dense labeling with global image data
dsl_dl('dataDir', imdb.dataDirDL,...
'expDir', expDirDL,...
'modelDir', modelDir,...
'gpus', gpus);

%% Step 2 CCN: sparse labeling with superpixel-wise low-level features
dsl_sl('dataDir', imdb.matDir,...
'expDir', expDirSL,...
'spDir', imdb.spDir,...
'modelDir', modelDir,...
'gpus', gpus);

%% Step 3 DCN: sparse labeling with results of former 2 steps as prior knowledge
dsl_dc('dataDir', imdb.dataDirDC,...
'expDir', expDirDC,...
'spDir', imdb.spDir,...
'spFullDir', imdb.spFullDir,...
'modelDir', modelDir,...
'locFcnDir', expDirDL,...
'locCcnDir', expDirSL,...
'gpus', gpus);

%% Delete temp files
% Comment the following line for fast re-perform
dsl_clear;
